<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="hp-PC" name="com.advertise.tests.TestBackCatcher2" tests="2" failures="0" timestamp="19 Jan 2016 11:58:45 GMT" time="361.443" errors="2">
  <testcase name="testBackcatcher2ForDesktopIY" time="127.343" classname="com.advertise.tests.TestBackCatcher2">
    <error type="java.lang.AssertionError" message="Backcatcher2 is not fired !! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Backcatcher2 is not fired !! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.advertise.utils.TestCaseUtils.verifyResult(TestCaseUtils.java:68)
	at com.advertise.tests.TestBackCatcher2.testBackcatcher2(TestBackCatcher2.java:312)
	at com.advertise.tests.TestBackCatcher2.testBackcatcher2ForDesktopIY(TestBackCatcher2.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testBackcatcher2ForDesktopIY -->
  <testcase name="testBackcatcher2ForDesktopIY" time="234.100" classname="com.advertise.tests.TestBackCatcher2">
    <error type="java.lang.AssertionError" message="No POP action triggered !! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No POP action triggered !! expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.advertise.utils.TestCaseUtils.verifyResult(TestCaseUtils.java:68)
	at com.advertise.tests.TestBackCatcher2.testBackcatcher2(TestBackCatcher2.java:207)
	at com.advertise.tests.TestBackCatcher2.testBackcatcher2ForDesktopIY(TestBackCatcher2.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testBackcatcher2ForDesktopIY -->
</testsuite> <!-- com.advertise.tests.TestBackCatcher2 -->
